name: Post Build Sauce Labs Tests
on:
  schedule:
    - cron: '*/59 * * * *'
  workflow_dispatch:
  
env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  working-directory: ./webdriver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache-npm-packages
        with:
          path: |
            **/webdriver/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/webdriver/package.json') }}

      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: |
          npm install
        working-directory: ${{env.working-directory}}

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: |
            build
          key: ${{ runner.os }}-${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: |
          npm install
        working-directory: ${{env.working-directory}}
        
      - name: Run WDIO Cross-Platform Tests
        run: |
          npx wdio run ./wdio.conf.js
