name: Post Build Sauce Labs Tests
on:
  schedule:
    - cron: '*/59 * * * *'

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: |-
          cd webdriver/
          npm install

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: |
            build
          key: ${{ runner.os }}-${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run WDIO Cross-Platform Tests
        run: |-
          cd webdriver/
          npx wdio run wdio.conf.js

