apiVersion: v1alpha
kind: cypress
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    name: Testing Sauce Docs
    tags:
      - e2e
      - technical-content-team
    build: Release $CI_COMMIT_SHORT_SHA
cypress:
  version: 6.6.0
  configFile: "tests/cypress.json"
suites:
  - name: "all chrome"
    browser: "chrome"
    platformName: "Windows 10"
    config:
      testFiles: [ "**/*.*" ]
